version: '3.4'

services:
  nodejsexpresssequelizemysql:
    image: nodejsexpresssequelizemysql
    build:
      context: api
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 2021:2021
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "server.js"]
